### ISSUE TITLE
Use binder to serve jupyter notebooks online

### ISSUE THREAD

**Issue by spflueger** [ComPWA/tensorwaves#53]
https://mybinder.org/

This would be great feature for new users to give it a try and hopefully make a good first impression

**[Estimated effort: 1d]**

**Comment by redeboer** [comment]
At least one problem with mybinder seems to be that reST cells don't render.

At any rate, here are two previews:

**`tensorwaves`**
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ComPWA/tensorwaves/master?filepath=examples%2Fworkflow)

**`expertsystem`**
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ComPWA/expertsystem/master?filepath=examples%2Fjupyter%2FQuickStart.ipynb)

**Comment by redeboer** [comment]
Note that the binders don't work because of the way we use the [`environment.yml`](https://github.com/ComPWA/expertsystem/blob/master/environment.yml) files. We use them only to define a virtual Conda environment in which you install `tensorwaves`/`expertsystem` in ['developer mode'](https://pwa.readthedocs.io/projects/expertsystem/en/0.1.2-alpha/install/install.html#developer-mode), i.e. just taking the source code folder as the package definition -- not installing the package.

The problem is that binder uses that `environment.yml` file as a complete definition to set up a Conda environment, meaning binder also expects you to install the package (`expertsystem`/`tensorwaves`) through that `environment.yml` definition file.

**Comment by redeboer** [comment]
@spflueger If you're sure `pip install -e .` works well, we may be able to run this from the `environment.yml` file.

**Comment by redeboer** [comment]
> @spflueger If you're sure pip install -e . works well, we may be able to run this from the environment.yml file.

This problem can be solved once we use the setup procedure introduced in https://github.com/ComPWA/expertsystem/pull/102
